### ISSUE TITLE
Reqest: Set Port

### ISSUE THREAD

**Issue by arnicas** [koaning/bulk#13]
I know I can mod the code quickly to do this, but can you allow a port so I can run it remotely on a vm with control over that.
Thanks!

**Comment by koaning** [comment]
I recall having some issues with the Bokeh api to get that port feature working properly as I rushed to a first release for this project. But I totally agree the port feature should be in there. I'll gladly have a look at any PR, but I'm a bit time constrained for the next few weeks due to my parental leave. 

so. many. diapers.

**Comment by koaning** [comment]
Ah! Found it! 

This will be fixed by this pr: https://github.com/koaning/bulk/pull/17 and will be part of the new release. 

The bokeh docs were a bit vague, but it seems like you need to pass the port as a `**kwarg` to the `Server` which in turn will pass it to Tornado. Kwargs are cool, but it'd be even cooler if `port=` would simply be documented.

**Comment by arnicas** [comment]
thank you!
