### ISSUE TITLE
JS code for update

### ISSUE THREAD

**Issue by amantyag** [koaning/bulk#16]
I am new to Bokeh, can you provide javascript code for the update function callback, that way the code can be used for standalone HTML/JS too
   def update(attr, old, new):
            """Callback used for plot update when lasso selecting"""
            global highlighted_idx
            subset = df.iloc[new]
            highlighted_idx = new
            subset = subset.iloc[np.random.permutation(len(subset))]
            source.data = subset

Thank you.

**Comment by koaning** [comment]
I'm also new to Bokeh, so I'm not the right person to ask about javascript code. But I think the whole point of their API is that this is abstracted away so that you, as a user, don't have to worry about it. 

This project might explore the javascript API in the future, but this is currently out of scope.
