### ISSUE TITLE
Request:  Save all columns from selected rows, not just text.

### ISSUE THREAD

**Issue by arnicas** [koaning/bulk#19]
I'd rather preserve the rest of the columns from my df along with my subset of selections saved.  I have other options to request too - what if you had a config yaml file for these?

**Comment by koaning** [comment]
A config file is possible. What's the main argument against having command line flags for these?

**Comment by arnicas** [comment]
Command line or config is fine... I just felt I was proposing a lot of options and maybe moving away from a huge command line would be an idea.  Doesn't matter to me...

**Comment by koaning** [comment]
The more that I'm thinking about it, the more that I'm wondering if it's perhaps not better default behavior to keep all the columns.

**Comment by rsbohn** [comment]
+1 This would be great when going back and forth between prodigy and BULK.

**Comment by jefromyers** [comment]
I'm not sure if this is still being discussed. I added a `save-all-columns` flag to the command line arguments to help me with this issue. Happy to submit a PR but wasn't sure if you decided not to go in this direction and thought I'd check first.

**Comment by koaning** [comment]
I think having all columns be saved is appropriate for the base behavior. I'll gladly welcome a PR but I'm also interested in rewriting the code base a bit so that parts are a bit more modular. Right now you might need to change the code in both the image recipe and the text one to add this feature. That feels like that should happen in one place. 

The downside to all this is that my newborn is preventing me to work on this project now that he's teething.
